/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gol;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test void appHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
    

    //Test that initial grtid

    //Should oscillate as seen in Conway GOL wiki
    @Test void testOscillator() {
        boolean[][] initial = {{false, false, false, false, false},
                                {false, false, true, false, false},
                                {false, false, true, false, false},
                                {false, false, true, false, false},
                                {false, false, false, false, false}};
        
        boolean[][] result = {{false, false, false, false, false},
                                {false, false, false, false, false},
                                {false, true, true, true, false},
                                {false, false, false, false, false},
                                {false, false, false, false, false}};
        
        
                        
        // Create an empty population that we can fill so that we can 
        // apply our ruleset to it
        Population testPopulation = new Population(5,5);

        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                testPopulation.setCell(i, j, initial[i][j]);
            }
        }

        testPopulation = ConwayRules.evolve(testPopulation);
        
        // Go through the grid and ensure the rules worked correctly by checking
        // that each of the cells match the result grid.
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                System.out.print(testPopulation.getCell(i, j) + " ");
                System.out.print(result[i][j] + " next ");
                assertEquals(testPopulation.getCell(i, j), result[i][j]);
            }

            System.out.println();
        }
    }
}
